# Site settings
title: Blair's Arborist Equipment
description: >
  Serving the Trees Since 1911
author: Don Blair
email: sales@blairsae.com
url: https://blairsae.com
address:
  - street: 16800 Blake Road
  - city: Hagerstown
  - state: MD
image:
  url: "https://images.blairsae.com"
turnstile:
  site_key: "0x4AAAAAAD2AxbmCv2D9Ev7Q"
mailer:
  url: "https://api.blairsae.com/mailer"

# Build settings
markdown: kramdown
sass:
  style: compact
plugins:
  - jekyll-seo-tag
exclude:
  - "*.swp"
  - Gemfile*
  - Pipfile*
  - Makefile
  - README.md
  - .gitignore
  - .jekyll-metadata
  - build/
  - .bundle/
  - .git/
  - vendor/
